version: '3.8'

services:
  backend:
    build:
      context: ./src
    ports:
      - "8080:8080"
  
  frontend:
    build:
      context: ../frontend/hello-event-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
